kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: alvrme/alpine-android:android-33
    pull: if-not-exists
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ./gradlew publish --warning-mode all --rerun-tasks
    when:
      event: [ tag ]
    environment:
      ORG_GRADLE_PROJECT_mavenCentralUsername:
        from_secret: MAVEN_CENTRAL_USERNAME
      ORG_GRADLE_PROJECT_mavenCentralPassword:
        from_secret: MAVEN_CENTRAL_PASSWORD
      ORG_GRADLE_PROJECT_signingInMemoryKey:
        from_secret: SIGNING_KEY
      SONATYPE_AUTOMATIC_RELEASE: true
      SONATYPE_HOST: DEFAULT

  - name: unitTest
    image: alvrme/alpine-android:android-33
    pull: if-not-exists
    commands:
      - ./gradlew test --stacktrace --warning-mode=all
    when:
      event: [ push ]
