kind: pipeline
type: docker
name: default

steps:
  - name: unitTest
    image: androidsdk/android-33
    pull: if-not-exists
      commands:
        - bash ./gradlew test --stacktrace --warning-mode=all
      when:
        event:
          - push

  - name: publish-snapshot
    image: alvrme/alpine-android:android-33
    pull: if-not-exists
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ./gradlew publish --no-daemon --no-parallel
      - ./gradlew closeAndReleaseRepository
    when:
      branch: [ master ]
      event: [ push ]
    environment:
      ORG_GRADLE_PROJECT_mavenCentralUsername:
        from_secret: MAVEN_CENTRAL_USERNAME
      ORG_GRADLE_PROJECT_mavenCentralPassword:
        from_secret: MAVEN_CENTRAL_PASSWORD
      ORG_GRADLE_PROJECT_signingInMemoryKey:
        from_secret: SIGNING_KEY
